name: Build and Release .NET Console App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        working-directory: D:/a/Galaxy-Conqueror/Galaxy-Conqueror/client/Galaxy.Conqueror.Client
        run: dotnet restore

      - name: Build
        working-directory: D:/a/Galaxy-Conqueror/Galaxy-Conqueror/client/Galaxy.Conqueror.Client
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Zip output
        run: zip -r release-artifact.zip ./publish

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Galaxy Conqueror CLI application
          files: release-artifact.zip
        env:
         GITHUB_TOKEN: ${{ secrets.TEST_CLI_DEPLOY }}
