name: Build and Release .NET Console App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-exe:
    name: Build EXE
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SHOW FILES
        run: pwd

      - name: List repo contents
        run: ls -R

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        working-directory: D:/a/Galaxy-Conqueror/Galaxy-Conqueror/client/Galaxy.Conqueror.Client
        run: dotnet restore

      - name: Build and publish EXE
        working-directory: D:/a/Galaxy-Conqueror/Galaxy-Conqueror/client/Galaxy.Conqueror.Client
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Galaxy-Conqueror
          path: D:/a/Galaxy-Conqueror/Galaxy-Conqueror/client/Galaxy.Conqueror.Client/**/bin/Release/net*/win-x64/publish/*.exe

  release:
    name: Update GitHub Release
    runs-on: ubuntu-latest
    needs: build-exe

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download EXE Artifact
        uses: actions/download-artifact@v4
        with:
          name: Galaxy-Conqueror
          path: app-release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Stable .NET console app release."
          draft: false
          prerelease: false
          files: app-release/*.exe

