name: Migrate New DB Schema

on:
  push:
    branches:
      - migrations

jobs:
  migrate:
    name: Run Flyway Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Java (required for Flyway)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flyway CLI
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.22.3/flyway-commandline-9.22.3-linux-x64.tar.gz -o flyway.tar.gz
          tar -xzf flyway.tar.gz
          sudo mv flyway-9.22.3 /opt/flyway
          sudo ln -s /opt/flyway/flyway /usr/local/bin/flyway

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch DB credentials from Secrets Manager
        id: fetch-db-creds
        run: |
          secret=$(aws secretsmanager get-secret-value --secret-id galaxy-conqueror-rds-db-secrets --query SecretString --output text)
          echo "$secret"
          username=$(echo $secret | jq -r .username)
          password=$(echo $secret | jq -r .password)

          echo "DB_USERNAME=$username" >> $GITHUB_ENV
          echo "DB_PASSWORD=$password" >> $GITHUB_ENV

      - name: Run Flyway Migrations
        run: |
          flyway \
            -url="jdbc:postgresql://${{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}" \
            -user="${{ env.DB_USERNAME }}" \
            -password="${{ env.DB_PASSWORD }}" \
            -locations="filesystem:./flyway/migrations" \
            migrate
